### ISSUE TITLE
Could not find 'nsz_v4.0.1_win64_portable'! (error 16)

### ISSUE THREAD

**Issue by ZhenyuXiao** [Dumpinground/emulator-tools#1]
## Bug Report

**Package Name:** 'nsz' (4.6.1)

### Current Behaviour

Could not find 'nsz_v4.0.1_win64_portable'! (error 16)

### Expected Behaviour

no such error

### Additional context/output

└─Δ scoop install Dumpinground_emulator-tools/nsz
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'nsz' (4.6.1) [64bit] from 'Dumpinground_emulator-tools' bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c6fc7b|OK  |   4.3MiB/s|C:/Users/Gauss/scoop/cache/nsz#4.6.1#ef81909.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of nsz_v4.6.1_win64_portable.zip ... ok.
Extracting nsz_v4.6.1_win64_portable.zip ... Exception: C:\Users\Gauss\scoop\apps\scoop\current\lib\core.ps1:889
Line |
 889 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'nsz_v4.0.1_win64_portable'! (error 16)

### Possible Solution

edit the nsz.json

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Dumpinground** [comment]
Made a small change to fix. Please run `scoop update` and try `scoop install nsz` again.  😊
